### PR TITLE
Added hover effect while dragging

### PR DESCRIPTION
**Pull request by Rahul-ku-Mo**
Added the hover effect on the Parent blocks when the dragged element is on top of it.

### CODE REVIEW

**Review by surajair — CHANGES_REQUESTED** [review]
Please remove the pnpm-lock file and add a video of the feature to PR

**Comment by Rahul-ku-Mo** [comment]
https://github.com/chaibuilder/sdk/assets/83443927/ed4cea7d-44dd-4b93-88c0-2d5ec8b83555


This is what it looks like. Moving the nodes over a parent block would change its background and text. So the user can know that It is a drop zone.

**Comment by Rahul-ku-Mo** [comment]
https://github.com/chaibuilder/sdk/assets/83443927/25feb033-7885-4e14-a760-6948bf5ffd10

**Comment by Rahul-ku-Mo** [comment]
I have also included the opacity decrement when a node is grabbed and was able to create the custom grab node. (ghost). 


https://github.com/chaibuilder/sdk/assets/83443927/0c9031d0-2638-4983-a008-5ad9e30bbf39

**Pull request merged**
